[build]
  publish = "github-pages"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/material-predict"
  to = "/.netlify/functions/material-predict"
  status = 200
  force = true

[[redirects]]
  from = "/api/scienceone"
  to = "/.netlify/functions/scienceone"
  status = 200
  force = true

[[redirects]]
  from = "/api/scienceone/*"
  to = "/.netlify/functions/scienceone/:splat"
  status = 200
  force = true
